### ISSUE TITLE
Change names of doctors in "Our Best Deaprtments" sections

### ISSUE THREAD

**Issue by UmerManager** [TaoFruit/alliedcare#137]
Change the names of all doctors showing on images on our services page.

Page link: https://alliedcare.org/services.html

For Example: EMILY NORA replace it with Dr. NORA
![image](https://user-images.githubusercontent.com/111144473/205903911-be8bc0e6-48b6-46b3-9a92-cad8a932e4d1.png)

**Comment by yennefer-m** [comment]
I have updated my PR.
